const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let catalogue=[],filtered=[],statuses=JSON.parse(localStorage.getItem('sv-statuses')||'{}'),details=JSON.parse(localStorage.getItem('sv-details')||'{}');
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);const save=()=>{localStorage.setItem('sv-statuses',JSON.stringify(statuses));localStorage.setItem('sv-details',JSON.stringify(details))};
async function init(){catalogue=await fetch('/data/catalogue.json').then(r=>r.json());catalogue.forEach(x=>{if(!statuses[x.id])statuses[x.id]='Need'});fillFilters();bind();render();checkConnections();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js')}
function fillFilters(){[...new Set(catalogue.map(x=>x.type).filter(Boolean))].sort().forEach(v=>$('#typeFilter').add(new Option(v,v)));[...new Set(catalogue.map(x=>x.character).filter(Boolean))].sort().forEach(v=>$('#characterFilter').add(new Option(v,v)))}
function bind(){$$('.tab').forEach(b=>b.onclick=()=>showView(b.dataset.view));['searchInput','statusFilter','typeFilter','characterFilter','sortBy'].forEach(id=>$('#'+id).addEventListener(id==='searchInput'?'input':'change',render));$('#exportBtn').onclick=$('#settingsExport').onclick=exportData;$('#importInput').onchange=importData;$('#resetBtn').onclick=()=>{if(confirm('Reset all statuses and personal details?')){statuses={};details={};save();location.reload()}};$('#refreshReleases').onclick=loadReleases;$('.dialog-close').onclick=()=>$('#detailDialog').close()}
function showView(v){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');if(v==='releases')loadReleases()}
function render(){const q=$('#searchInput').value.toLowerCase(),sf=$('#statusFilter').value,tf=$('#typeFilter').value,cf=$('#characterFilter').value;filtered=catalogue.filter(x=>(!q||[x.name,x.number,x.character,x.exclusive,x.variant,x.line].join(' ').toLowerCase().includes(q))&&(sf==='all'||statuses[x.id]===sf)&&(tf==='all'||x.type===tf)&&(cf==='all'||x.character===cf));const sort=$('#sortBy').value;filtered.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='value-desc'?b.estimatedValue-a.estimatedValue:String(a.number).localeCompare(String(b.number),undefined,{numeric:true}));const host=$('#catalogue');host.innerHTML='';filtered.forEach(x=>host.append(card(x)));$('#resultCount').textContent=`${filtered.length} items`;stats()}
function card(x){const n=$('#cardTemplate').content.cloneNode(true),art=n.querySelector('.art');n.querySelector('.art-number').textContent=x.number?`#${String(x.number).replace(/^#/,'')}`:'—';n.querySelector('.character').textContent=x.character;n.querySelector('.name').textContent=x.name;n.querySelector('.meta').innerHTML=[x.type,x.variant,x.exclusive].filter(Boolean).map(v=>`<span>${esc(v)}</span>`).join('');n.querySelector('.value').textContent=money(x.estimatedValue);n.querySelectorAll('[data-status]').forEach(b=>{b.classList.toggle('active',statuses[x.id]===b.dataset.status);b.onclick=()=>{statuses[x.id]=b.dataset.status;save();render()}});n.querySelector('.price-btn').onclick=()=>priceCheck(x);art.onclick=()=>openDetails(x);return n}
function stats(){const total=catalogue.length,owned=catalogue.filter(x=>statuses[x.id]==='Owned'),incoming=catalogue.filter(x=>statuses[x.id]==='Incoming').length,need=catalogue.filter(x=>statuses[x.id]==='Need').length,p=Math.round(owned.length/total*100);$('#totalCount').textContent=total;$('#ownedCount').textContent=owned.length;$('#incomingCount').textContent=incoming;$('#needCount').textContent=need;$('#ownedValue').textContent=money(owned.reduce((s,x)=>s+(details[x.id]?.manualValue??x.estimatedValue),0));$('#progressPct').textContent=p+'%';$('#progressRing').style.setProperty('--p',p+'%')}
function openDetails(x){const d=details[x.id]||{};$('#detailContent').innerHTML=`<p class="kicker">${esc(x.character)}</p><h2>${esc(x.name)} ${x.number?'#'+esc(String(x.number).replace(/^#/,'')):''}</h2><p>${esc([x.line,x.type,x.variant,x.exclusive].filter(Boolean).join(' · '))}</p><label>Purchase price (USD)<input id="purchasePrice" type="number" value="${d.purchasePrice||''}"></label><label>Manual market value (USD)<input id="manualValue" type="number" value="${d.manualValue||''}"></label><label>Notes<textarea id="personalNotes">${esc(d.notes||'')}</textarea></label><button id="saveDetails" class="button">Save details</button>`;$('#detailContent').querySelectorAll('input,textarea').forEach(i=>{i.style.cssText='width:100%;margin:6px 0 14px;padding:12px;border-radius:10px;border:1px solid #273142;background:#181e29;color:white'});$('#saveDetails').onclick=()=>{details[x.id]={purchasePrice:Number($('#purchasePrice').value)||0,manualValue:Number($('#manualValue').value)||0,notes:$('#personalNotes').value};save();$('#detailDialog').close();render()};$('#detailDialog').showModal()}
async function priceCheck(x){$('#detailContent').innerHTML=`<p class="kicker">EBAY PRICE CHECK</p><h2>${esc(x.name)} ${x.number?'#'+esc(String(x.number).replace(/^#/,'')):''}</h2><p>Checking current active listings…</p>`;$('#detailDialog').showModal();try{const r=await fetch('/api/ebay-price?'+new URLSearchParams({name:x.name,number:x.number||'',exclusive:x.exclusive||''}));const j=await r.json();if(!r.ok)throw Error(j.error||'Price check failed');$('#detailContent').innerHTML=`<p class="kicker">ACTIVE LISTING ESTIMATE</p><h2>${esc(x.name)}</h2><div class="price-results"><div class="price-row"><span>Median asking price</span><strong>${money(j.median)}</strong></div><div class="price-row"><span>Average asking price</span><strong>${money(j.average)}</strong></div><div class="price-row"><span>Comparable listings</span><strong>${j.count}</strong></div><div class="price-row"><span>Range</span><strong>${money(j.low)}–${money(j.high)}</strong></div></div><p>${esc(j.note)}</p><a class="button" target="_blank" rel="noopener" href="${j.searchUrl}">View on eBay</a>`}catch(e){$('#detailContent').innerHTML=`<h2>Price check unavailable</h2><p>${esc(e.message)}</p><p>Add EBAY_CLIENT_ID and EBAY_CLIENT_SECRET in Vercel project settings.</p>`}}
async function loadReleases(){const host=$('#releaseList');host.innerHTML='';$('#releaseStatus').textContent='Loading release queue…';try{const r=await fetch('/api/releases');const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to load releases');$('#releaseStatus').textContent=j.items.length?`${j.items.length} candidate release(s) waiting for review.`:'No new candidates found.';$('#releaseBadge').textContent=j.items.length;$('#releaseBadge').classList.toggle('hidden',!j.items.length);j.items.forEach(x=>{const el=document.createElement('article');el.className='card';el.innerHTML=`<div class="art"><span class="art-number">${esc(x.box_number||'NEW')}</span><div class="web-lines"></div></div><div class="card-body"><p class="character">FUNKO CANDIDATE</p><h3>${esc(x.name)}</h3><p class="meta">${esc(x.product_type||'')} ${esc(x.source_url||'')}</p><div class="release-actions"><button class="button approve">Approve</button><button class="button secondary ignore">Ignore</button></div></div>`;el.querySelector('.approve').onclick=()=>reviewRelease(x.id,'approved');el.querySelector('.ignore').onclick=()=>reviewRelease(x.id,'ignored');host.append(el)})}catch(e){$('#releaseStatus').textContent=e.message}}
async function reviewRelease(id,status){await fetch('/api/releases',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});loadReleases()}
async function checkConnections(){try{const j=await fetch('/api/health').then(r=>r.json());$('#connectionStatus').textContent=`eBay: ${j.ebay?'connected':'not configured'} · Supabase: ${j.supabase?'connected':'not configured'} · Cron secret: ${j.cron?'configured':'not configured'}`}catch{$('#connectionStatus').textContent='Backend not available until deployed.'}}
function exportData(){const blob=new Blob([JSON.stringify({version:1,statuses,details,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='spideyvault-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{const j=JSON.parse(r.result);statuses=j.statuses||{};details=j.details||{};save();render();alert('Backup imported')}catch{alert('Invalid backup file')}};r.readAsText(f)}
function esc(v){return String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}init();