import { catalogue } from './catalogue.js';
const KEY='spideyvault-v1';
const state={filter:'All',type:'All',query:'',sort:'name',selected:null};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{items:{},updatedAt:null}}catch{return {items:{},updatedAt:null}}};
let userData=load();
const personal=item=>userData.items[item.id]||{status:item.initialStatus||'Need',purchasePrice:'',notes:'',updatedAt:''};
const save=()=>{userData.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(userData));};
const money=(n,c='USD')=>new Intl.NumberFormat('en-GB',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number(n)||0);
const toast=m=>{const el=$('#toast');el.textContent=m;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)};
function merged(){return catalogue.map(x=>({...x,...personal(x)}))}
function stats(){const all=merged(),owned=all.filter(x=>x.status==='Owned'),need=all.filter(x=>x.status==='Need'),incoming=all.filter(x=>x.status==='Incoming');return{total:all.length,owned:owned.length,need:need.length,incoming:incoming.length,value:owned.reduce((a,x)=>a+(Number(x.estimatedValue)||0),0),spent:owned.reduce((a,x)=>a+(Number(x.purchasePrice)||0),0)}}
function renderStats(){const s=stats();$('#stats').innerHTML=[['Catalogue',s.total],['Owned',s.owned],['Incoming',s.incoming],['Est. value',money(s.value)]].map(([l,v])=>`<div class="stat"><strong>${v}</strong><span>${l}</span></div>`).join('');const pct=s.total?Math.round(s.owned/s.total*100):0;$('#progressBar').style.width=pct+'%';$('#progressLabel').textContent=`${pct}% complete`}
function card(x){return `<button class="card" data-id="${x.id}"><span class="num">${x.number||'NO NUMBER'}</span><h3>${x.name}</h3><div class="meta">${x.variant||'Standard'}<br>${x.line}</div><span class="status ${x.status}">${x.status}</span></button>`}
function renderRecent(){const updated=merged().filter(x=>x.updatedAt).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,8);$('#recentGrid').innerHTML=updated.length?updated.map(card).join(''):'<div class="panel"><h2>Your vault is ready</h2><p>Open the catalogue and mark your first Pop as Owned or Incoming.</p></div>'}
function filtered(){let a=merged();if(state.filter!=='All')a=a.filter(x=>x.status===state.filter);if(state.type!=='All')a=a.filter(x=>x.type===state.type);if(state.query){const q=state.query.toLowerCase();a=a.filter(x=>[x.name,x.character,x.number,x.line,x.variant,x.exclusive].join(' ').toLowerCase().includes(q))}a.sort((x,y)=>{if(state.sort==='number'){const nx=parseInt(x.number?.replace(/\D/g,''),10),ny=parseInt(y.number?.replace(/\D/g,''),10);return (Number.isNaN(nx)?999999:nx)-(Number.isNaN(ny)?999999:ny)||x.name.localeCompare(y.name)}if(state.sort==='value-desc')return y.estimatedValue-x.estimatedValue;if(state.sort==='updated')return (y.updatedAt||'').localeCompare(x.updatedAt||'');return x.name.localeCompare(y.name)});return a}
function renderCatalogue(){const a=filtered();$('#resultCount').textContent=`${a.length} items`;$('#catalogueGrid').innerHTML=a.map(card).join('')||'<div class="panel"><h2>No matches</h2><p>Try changing the search or filters.</p></div>'}
function openDetail(id){const x=merged().find(i=>i.id===id);state.selected=x.id;$('#detailContent').innerHTML=`<div class="detail"><div class="detail-top"><div><span class="pill">${x.type}</span><h2>${x.name}</h2><p class="meta">${x.character}</p></div><button class="close" id="closeDialog">✕</button></div><dl><dt>Pop number</dt><dd>${x.number||'—'}</dd><dt>Line / set</dt><dd>${x.line||'—'}</dd><dt>Variant</dt><dd>${x.variant||'—'}</dd><dt>Exclusive</dt><dd>${x.exclusive||'—'}</dd><dt>Estimated value</dt><dd>${money(x.estimatedValue,x.valueCurrency)}</dd></dl><p class="eyebrow">COLLECTION STATUS</p><div class="status-switch">${['Need','Owned','Incoming'].map(s=>`<button data-set-status="${s}" class="${x.status===s?'active':''}">${s}</button>`).join('')}</div><label class="field">Purchase price<input id="purchasePrice" type="number" inputmode="decimal" min="0" step="0.01" value="${x.purchasePrice||''}" placeholder="0.00"></label><label class="field">Personal notes<textarea id="personalNotes" placeholder="Condition, sticker, seller, autograph details…">${x.notes||''}</textarea></label><button class="primary save" id="saveDetail">Save changes</button></div>`;$('#detailDialog').showModal()}
function setupTypes(){const types=[...new Set(catalogue.map(x=>x.type))].sort();$('#typeFilter').innerHTML='<option value="All">All types</option>'+types.map(x=>`<option>${x}</option>`).join('')}
function navigate(view){$$('.view').forEach(x=>x.classList.remove('active'));$(`#${view}View`).classList.add('active');$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.nav===view));if(view==='catalogue')renderCatalogue();scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav)navigate(nav.dataset.nav);const c=e.target.closest('.card');if(c)openDetail(c.dataset.id);if(e.target.id==='closeDialog')$('#detailDialog').close();if(e.target.dataset.setStatus){$$('[data-set-status]').forEach(b=>b.classList.toggle('active',b===e.target))}if(e.target.id==='saveDetail'){const status=$('[data-set-status].active').dataset.setStatus;userData.items[state.selected]={status,purchasePrice:$('#purchasePrice').value,notes:$('#personalNotes').value,updatedAt:new Date().toISOString()};save();$('#detailDialog').close();renderAll();toast('Vault updated')}if(e.target.matches('#statusFilters .chip')){$$('#statusFilters .chip').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');state.filter=e.target.dataset.status;renderCatalogue()}});
$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;renderCatalogue()});$('#typeFilter').addEventListener('change',e=>{state.type=e.target.value;renderCatalogue()});$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderCatalogue()});
$('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({app:'SpideyVault',version:1,exportedAt:new Date().toISOString(),data:userData},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`spideyvault-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup exported')});
$('#importInput').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;const j=JSON.parse(await file.text());if(j.app!=='SpideyVault'||!j.data?.items||typeof j.data.items!=='object')throw Error();if(!confirm('Import this backup and replace the collection data currently stored on this device?'))return;userData=j.data;save();renderAll();toast('Backup restored')}catch{toast('Invalid backup file')}finally{e.target.value=''}});
$('#resetBtn').addEventListener('click',()=>{if(confirm('Reset all local collection data?')){userData={items:{},updatedAt:null};save();renderAll();toast('Vault reset')}});
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
function renderAll(){renderStats();renderRecent();renderCatalogue()}setupTypes();renderAll();
